Repository The-Ham-Project/BE, pull requests merged in 2024-04, with the labels that each got.

#21 feat: 함께쓰기 게시글 수정 기능
  src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
  src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
  src/main/java/com/hanghae/theham/domain/rental/entity/Rental.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
Labels: feature

#24 feat: 소셜 로그인 기능 (카카오, 네이버, 구글)
  build.gradle
  src/main/java/com/hanghae/theham/domain/auth/controller/OAuthController.java
  src/main/java/com/hanghae/theham/domain/auth/dto/MemberDTO.java
  src/main/java/com/hanghae/theham/domain/auth/service/OAuthService.java
  src/main/java/com/hanghae/theham/domain/auth/service/type/OAuthType.java
  src/main/java/com/hanghae/theham/domain/member/entity/Member.java
  src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: feature

#27 feat: 소셜 로그인 시큐리티 적용
  src/main/java/com/hanghae/theham/domain/member/controller/MemberController.java
  src/main/java/com/hanghae/theham/domain/member/controller/docs/MemberControllerDocs.java
  src/main/java/com/hanghae/theham/domain/member/service/GoogleService.java
  src/main/java/com/hanghae/theham/domain/member/service/KakaoService.java
  src/main/java/com/hanghae/theham/domain/member/service/NaverService.java
  src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
  src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
  src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
Labels: feature

#30 feat: 회원 좌표 갱신 기능
  src/main/java/com/hanghae/theham/domain/member/controller/MemberController.java
  src/main/java/com/hanghae/theham/domain/member/controller/docs/MemberControllerDocs.java
  src/main/java/com/hanghae/theham/domain/member/dto/MemberRequestDto.java
  src/main/java/com/hanghae/theham/domain/member/dto/MemberResponseDto.java
  src/main/java/com/hanghae/theham/domain/member/entity/Member.java
  src/main/java/com/hanghae/theham/domain/member/service/MemberService.java
  src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: feature

#31 feat: 카테고리별 함께쓰기 게시글 조회 기능
  src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
  src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
  src/main/java/com/hanghae/theham/domain/rental/entity/Rental.java
  src/main/java/com/hanghae/theham/domain/rental/entity/type/CategoryType.java
  src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
  src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
Labels: feature

#41 test: AuthService 테스트 코드 작성
  src/test/java/com/hanghae/theham/domain/member/service/AuthServiceTest.java
Labels: test

#42 feat: 마이페이지 내가 쓴 글 조회
  src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
  src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
  src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
Labels: feature

#43 feat: 함께쓰기 위치에 따라서 쿼리
  src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
  src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
  src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
Labels: feature

#46 refactor: Rental 관련된 내용 리팩토링
  src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
  src/main/java/com/hanghae/theham/domain/rental/scheduler/RentalScheduler.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
  src/main/java/com/hanghae/theham/global/exception/AwsS3Exception.java
  src/main/java/com/hanghae/theham/global/exception/CustomExceptionHandler.java
  src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
Labels: refactoring

#47 feat: 랜덤 닉네임 추가
  src/main/java/com/hanghae/theham/domain/member/repository/MemberRepository.java
  src/main/java/com/hanghae/theham/domain/member/service/GoogleService.java
  src/main/java/com/hanghae/theham/domain/member/service/KakaoService.java
  src/main/java/com/hanghae/theham/domain/member/service/NaverService.java
Labels: feature

#49 feat : 채팅방 조회 기능 및 메세지 전송 및 저장 기능 추가
  src/main/java/com/hanghae/theham/domain/chat/controller/ChatController.java
  src/main/java/com/hanghae/theham/domain/chat/controller/ChatRoomController.java
  src/main/java/com/hanghae/theham/domain/chat/controller/docs/ChatControllerDocs.java
  src/main/java/com/hanghae/theham/domain/chat/controller/docs/ChatRoomControllerDocs.java
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatRequestDto.java
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatResponseDto.java
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatRoomRequestDto.java
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/hanghae/theham/domain/chat/entity/Chat.java
  src/main/java/com/hanghae/theham/domain/chat/entity/ChatRoom.java
  src/main/java/com/hanghae/theham/domain/chat/repository/ChatRepository.java
  src/main/java/com/hanghae/theham/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/hanghae/theham/domain/chat/service/ChatRoomService.java
  src/main/java/com/hanghae/theham/domain/chat/service/ChatService.java
  src/main/java/com/hanghae/theham/global/config/WebSocketConfig.java
  src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
Labels: feature

#51 refactor: 소셜 로그인 전략 패턴 적용
  src/main/java/com/hanghae/theham/domain/member/controller/MemberController.java
  src/main/java/com/hanghae/theham/domain/member/controller/docs/MemberControllerDocs.java
  src/main/java/com/hanghae/theham/domain/member/dto/MemberResponseDto.java
  src/main/java/com/hanghae/theham/domain/member/entity/Member.java
  src/main/java/com/hanghae/theham/domain/member/repository/MemberRepository.java
  src/main/java/com/hanghae/theham/domain/member/service/SocialLoginService.java
  src/main/java/com/hanghae/theham/domain/member/strategy/GoogleLoginStrategy.java
  src/main/java/com/hanghae/theham/domain/member/strategy/KakaoLoginStrategy.java
  src/main/java/com/hanghae/theham/domain/member/strategy/NaverLoginStrategy.java
  src/main/java/com/hanghae/theham/domain/member/strategy/SocialLoginStrategy.java
  src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
Labels: refactoring

#53 fix : 채팅 message send request 변경 멤버Id -> 닉네임
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatRequestDto.java
  src/main/java/com/hanghae/theham/domain/chat/entity/ChatRoom.java
  src/main/java/com/hanghae/theham/domain/chat/service/ChatService.java
Labels: fix

#59 feat: 함께쓰기 좋아요 등록/삭제/조회 기능
  src/main/java/com/hanghae/theham/domain/like/controller/LikeController.java
  src/main/java/com/hanghae/theham/domain/like/controller/docs/LikeControllerDocs.java
  src/main/java/com/hanghae/theham/domain/like/dto/LikeRequestDto.java
  src/main/java/com/hanghae/theham/domain/like/dto/LikeResponseDto.java
  src/main/java/com/hanghae/theham/domain/like/entity/Like.java
  src/main/java/com/hanghae/theham/domain/like/repository/LikeRepository.java
  src/main/java/com/hanghae/theham/domain/like/service/LikeService.java
  src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
Labels: feature

#67 refactor: 함께쓰기 좋아요 기능 구조 변경
  src/main/java/com/hanghae/theham/domain/like/controller/LikeController.java
  src/main/java/com/hanghae/theham/domain/like/dto/LikeRequestDto.java
  src/main/java/com/hanghae/theham/domain/like/dto/LikeResponseDto.java
  src/main/java/com/hanghae/theham/domain/like/repository/LikeRepository.java
  src/main/java/com/hanghae/theham/domain/rental/controller/RentalRentalLikeController.java
  src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalLikeControllerDocs.java
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalLikeResponseDto.java
  src/main/java/com/hanghae/theham/domain/rental/entity/RentalLike.java
  src/main/java/com/hanghae/theham/domain/rental/repository/RentalLikeRepository.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalLikeService.java
  src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
Labels: refactoring

#68 feat: 함께쓰기 회원 위치 지역구 조회 기능 추가
  src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
  src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
  src/main/java/com/hanghae/theham/domain/rental/entity/Rental.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
  src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
Labels: feature

#76 chore: EC2 Timezone 설정
  .ebextensions/00-set-timezone.config
Labels: chore

#80 refactor: Slack 에러 메세지 개선, AOP 적용
  build.gradle
  src/main/java/com/hanghae/theham/global/config/ThreadPoolConfig.java
  src/main/java/com/hanghae/theham/global/dto/RequestInfo.java
  src/main/java/com/hanghae/theham/global/exception/CustomExceptionHandler.java
  src/main/java/com/hanghae/theham/global/slack/SlackNotification.java
  src/main/java/com/hanghae/theham/global/slack/SlackNotificationAspect.java
  src/main/resources/logback-dev.xml
Labels: refactoring

#82 test: 함께쓰기 게시글 작성 테스트 코드
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
  src/test/java/com/hanghae/theham/domain/rental/service/RentalServiceTest.java
Labels: test

#83 test: 함께쓰기 게시글 수정 테스트 코드
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
  src/test/java/com/hanghae/theham/domain/rental/service/RentalServiceTest.java
Labels: test

#84 test: 함께쓰기 게시글 삭제 테스트 코드
  src/test/java/com/hanghae/theham/domain/rental/service/RentalServiceTest.java
Labels: test

#85 test: 함께쓰기 게시글 조회 테스트 코드
  src/test/java/com/hanghae/theham/domain/rental/service/RentalServiceTest.java
Labels: test

#81 feat: 함께쓰기 검색기능 추가 / 글id, 제목, 작성자, 사진url
  src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
  src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
  src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalSearchService.java
Labels: feature

#87 refactor: 함께쓰기 서비스 레이어 리팩토링 및 오류 수정
  src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
  src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
  src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalSearchService.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
Labels: refactoring

#89 feat: 회원 정보 조회 기능 추가
  src/main/java/com/hanghae/theham/domain/member/controller/MemberController.java
  src/main/java/com/hanghae/theham/domain/member/controller/docs/MemberControllerDocs.java
  src/main/java/com/hanghae/theham/domain/member/dto/MemberResponseDto.java
  src/main/java/com/hanghae/theham/domain/member/service/MemberService.java
  src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
  src/test/java/com/hanghae/theham/domain/member/service/MemberServiceTest.java
Labels: feature

#91 test: Member Repository 테스트 코드 작성
  build.gradle
  src/test/java/com/hanghae/theham/domain/member/repository/MemberRepositoryTest.java
Labels: test

#92 feat: 채팅 토큰 인증 추가
  build.gradle
  src/main/java/com/hanghae/theham/domain/chat/controller/ChatController.java
  src/main/java/com/hanghae/theham/domain/chat/controller/ChatRoomController.java
  src/main/java/com/hanghae/theham/domain/chat/controller/docs/ChatControllerDocs.java
  src/main/java/com/hanghae/theham/domain/chat/controller/docs/ChatRoomControllerDocs.java
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatRequestDto.java
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatResponseDto.java
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/hanghae/theham/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/hanghae/theham/domain/chat/service/ChatRoomService.java
  src/main/java/com/hanghae/theham/domain/chat/service/ChatService.java
  src/main/java/com/hanghae/theham/global/config/WebSocketConfig.java
  src/main/java/com/hanghae/theham/global/websocket/WebSocketInterceptor.java
Labels: feature, refactoring, chore

#95 feat: 대여비, 보증금 1백만원 금액 제한
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
Labels: feature

#97 feat: 로그인 했을 시 회원의 위도, 경도 값 체크
  src/main/java/com/hanghae/theham/domain/member/controller/MemberController.java
  src/main/java/com/hanghae/theham/domain/member/controller/docs/MemberControllerDocs.java
  src/main/java/com/hanghae/theham/domain/member/dto/MemberResponseDto.java
  src/main/java/com/hanghae/theham/domain/member/service/MemberService.java
  src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
Labels: feature

#99 feat: 함께쓰기 상세 페이지 지역구 응답 값 추가
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
Labels: feature

#101 fix: 카테고리 ALL로 작성 가능했던 버그 수정
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
  src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
Labels: fix

#102 test: 함께쓰기 마이페이지 내가 쓴 글 조회 테스트 코드
  src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
  src/test/java/com/hanghae/theham/domain/rental/service/RentalServiceTest.java
Labels: test

#103 test: 함께쓰기 카테고리별 게시글 조회 테스트 코드
  src/test/java/com/hanghae/theham/domain/rental/service/RentalServiceTest.java
Labels: feature

#105 test: RentalRepository 테스트 코드 작성
  build.gradle
  src/test/java/com/hanghae/theham/domain/member/repository/MemberRepositoryTest.java
  src/test/java/com/hanghae/theham/domain/rental/repository/RentalRepositoryTest.java
Labels: test

#106 feat: 채팅 페이징 처리 추가
  src/main/java/com/hanghae/theham/domain/chat/controller/ChatRoomController.java
  src/main/java/com/hanghae/theham/domain/chat/controller/docs/ChatRoomControllerDocs.java
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatRoomRequestDto.java
  src/main/java/com/hanghae/theham/domain/chat/repository/ChatRepository.java
  src/main/java/com/hanghae/theham/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/hanghae/theham/domain/chat/service/ChatRoomService.java
Labels: feature

#109 feat: 함께쓰기 게시글 캐싱 작업
  build.gradle
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalImageResponseDto.java
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalLikeResponseDto.java
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
  src/main/java/com/hanghae/theham/domain/rental/entity/Rental.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
  src/main/java/com/hanghae/theham/global/config/RedisConfig.java
Labels: feature

#112 feat: 채팅 읽음 기능, 전체 조회시 안읽은 메세지 수 조회 기능 추가
  src/main/java/com/hanghae/theham/domain/chat/controller/ChatController.java
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatRequestDto.java
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatResponseDto.java
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/hanghae/theham/domain/chat/entity/Chat.java
  src/main/java/com/hanghae/theham/domain/chat/entity/ChatRoom.java
  src/main/java/com/hanghae/theham/domain/chat/entity/type/VisibleType.java
  src/main/java/com/hanghae/theham/domain/chat/repository/ChatRepository.java
  src/main/java/com/hanghae/theham/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/hanghae/theham/domain/chat/service/ChatRoomService.java
  src/main/java/com/hanghae/theham/domain/chat/service/ChatService.java
  src/main/java/com/hanghae/theham/global/config/WebSocketConfig.java
  src/main/java/com/hanghae/theham/global/websocket/ChatRoomParticipantManager.java
  src/main/java/com/hanghae/theham/global/websocket/WebSocketEventListener.java
  src/main/java/com/hanghae/theham/global/websocket/WebSocketInterceptor.java
Labels: feature

#116 fix: 채팅 unreadCount 반환주체 변경
  src/main/java/com/hanghae/theham/domain/chat/service/ChatRoomService.java
Labels: fix

#117 chore: 메시지 내부 내역 반환 순서 변경
  src/main/java/com/hanghae/theham/domain/chat/service/ChatRoomService.java
Labels: chore

#120 feat: 함께쓰기 상세 페이지 채팅하기 버튼 표시 유무
  src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
  src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalSearchService.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
  src/test/java/com/hanghae/theham/domain/rental/service/RentalServiceTest.java
Labels: feature

#121 feat: 채팅 상세조회 게시글 정보 추가
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/hanghae/theham/domain/chat/service/ChatRoomService.java
  src/main/java/com/hanghae/theham/domain/rental/repository/RentalImageRepository.java
Labels: feature

#122 feat: 채팅 채팅방 나가기 기능 추가
  src/main/java/com/hanghae/theham/domain/chat/controller/ChatRoomController.java
  src/main/java/com/hanghae/theham/domain/chat/controller/docs/ChatRoomControllerDocs.java
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/hanghae/theham/domain/chat/entity/Chat.java
  src/main/java/com/hanghae/theham/domain/chat/entity/ChatRoom.java
  src/main/java/com/hanghae/theham/domain/chat/entity/type/VisibleType.java
  src/main/java/com/hanghae/theham/domain/chat/repository/ChatRepository.java
  src/main/java/com/hanghae/theham/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/hanghae/theham/domain/chat/service/ChatRoomService.java
  src/main/java/com/hanghae/theham/domain/chat/service/ChatService.java
  src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
Labels: feature

#124 chore: 채팅방 상세조회 response 게시글 보증금, 대여비 추가
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatRoomResponseDto.java
Labels: chore

#126 feat: 함께쓰기 검색 기능 개수 반환 추가
  src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
  src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
  src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalSearchService.java
Labels: feature

#127 feat: 썸네일 처리 기능 추가
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalSearchService.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
Labels: feature

#129 fix: 채팅방 동시성 제어 버그 수정
  src/main/java/com/hanghae/theham/global/config/WebSocketConfig.java
  src/main/java/com/hanghae/theham/global/websocket/WebSocketEventListener.java
  src/main/java/com/hanghae/theham/global/websocket/WebSocketInterceptor.java
Labels: fix

#133 fix: 게시글 조회 Delete 적용
  src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalSearchService.java
Labels: fix

#134 feat: chat exception handle
  src/main/java/com/hanghae/theham/domain/chat/service/ChatRoomService.java
  src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
  src/main/java/com/hanghae/theham/global/config/WebSocketConfig.java
  src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
  src/main/java/com/hanghae/theham/global/websocket/WebSocketInterceptor.java
  src/main/java/com/hanghae/theham/global/websocket/dto/MessageErrorResponse.java
  src/main/java/com/hanghae/theham/global/websocket/exception/CustomMessageExceptionHandler.java
  src/main/java/com/hanghae/theham/global/websocket/exception/WebSocketErrorHandler.java
  src/main/java/com/hanghae/theham/global/websocket/exception/WebSocketException.java
Labels: feature

#138 refactor: Hibernate Spatial 적용하기
  build.gradle
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
  src/main/java/com/hanghae/theham/domain/rental/entity/Rental.java
  src/main/java/com/hanghae/theham/domain/rental/repository/RentalDistanceRepository.java
  src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalSearchService.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
  src/test/java/com/hanghae/theham/domain/rental/repository/RentalRepositoryTest.java
  src/test/java/com/hanghae/theham/domain/rental/service/RentalServiceTest.java
Labels: refactoring

#141 refactor: 함께쓰기 게시글 수정 로직 리펙토링
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
  src/main/java/com/hanghae/theham/domain/rental/repository/RentalImageRepository.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
Labels: refactoring

#142 fix: 게시글 삭제시 연관 채팅방 삭제
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatRoomRequestDto.java
  src/main/java/com/hanghae/theham/domain/chat/entity/ChatRoom.java
  src/main/java/com/hanghae/theham/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/hanghae/theham/domain/chat/service/ChatRoomService.java
  src/main/java/com/hanghae/theham/domain/chat/service/ChatService.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
  src/main/java/com/hanghae/theham/global/config/WebSocketConfig.java
  src/main/java/com/hanghae/theham/global/websocket/WebSocketInterceptor.java
  src/main/java/com/hanghae/theham/global/websocket/exception/WebSocketExceptionHandler.java
Labels: fix, refactoring

#144 feat: 함께쓰기 욕설 필터링 적용
  build.gradle
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
  src/main/java/com/hanghae/theham/global/util/BadWordFilteringUtil.java
  src/main/resources/badwords.txt
Labels: feature

#146 fix: 욕설 필터링 추가 후 배포 환경에서 500 에러 수정
  src/main/java/com/hanghae/theham/global/util/BadWordFilteringUtil.java
Labels: fix

#148 feat: 채팅 욕설 필터링 추가
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatRequestDto.java
  src/main/resources/badwords.txt
Labels: feature

#150 fix: 함께쓰기 카테고리 조회시 응답 값 영어로 수정
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
Labels: fix

#154 fix: 함께쓰기 페이징 캐싱 처리 된거 제거
  src/main/java/com/hanghae/theham/domain/rental/service/RentalCachingService.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
Labels: fix

#156 fix: cors 설정 변경
  src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
Labels: fix

#159 feat: SSE를 통한 채팅방 갱신 기능 & 새로운 메세지 알림 기능 추가
  src/main/java/com/hanghae/theham/domain/chat/controller/ChatController.java
  src/main/java/com/hanghae/theham/domain/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/hanghae/theham/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/hanghae/theham/domain/chat/service/ChatRoomService.java
  src/main/java/com/hanghae/theham/domain/chat/service/ChatService.java
  src/main/java/com/hanghae/theham/domain/notification/controller/NotificationController.java
  src/main/java/com/hanghae/theham/domain/notification/controller/docs/NotificationControllerDocs.java
  src/main/java/com/hanghae/theham/domain/notification/dto/NotificationResponseDto.java
  src/main/java/com/hanghae/theham/domain/notification/dto/type/NotificationType.java
  src/main/java/com/hanghae/theham/domain/notification/repository/EmitterRepository.java
  src/main/java/com/hanghae/theham/domain/notification/service/NotificationService.java
  src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
Labels: feature

#161 feat: 채팅방 안읽은 메세지 읽음시 알림 전송
  src/main/java/com/hanghae/theham/domain/chat/service/ChatRoomService.java
  src/main/java/com/hanghae/theham/domain/notification/dto/type/NotificationType.java
  src/main/java/com/hanghae/theham/domain/notification/service/NotificationService.java
Labels: feature

#163 feature: 회원 정보 수정 기능
  src/main/java/com/hanghae/theham/domain/member/controller/MemberController.java
  src/main/java/com/hanghae/theham/domain/member/controller/docs/MemberControllerDocs.java
  src/main/java/com/hanghae/theham/domain/member/dto/MemberRequestDto.java
  src/main/java/com/hanghae/theham/domain/member/entity/Member.java
  src/main/java/com/hanghae/theham/domain/member/repository/MemberRepository.java
  src/main/java/com/hanghae/theham/domain/member/service/MemberService.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
  src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
  src/main/java/com/hanghae/theham/global/service/S3Service.java
Labels: feature

#167 fix: 닉네임 수정 API 시큐리티 적용
  src/main/java/com/hanghae/theham/domain/member/dto/MemberRequestDto.java
  src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
Labels: fix

#171 feat: 함께쓰기 좋아요 조회 기능
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalLikeResponseDto.java
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
Labels: feature

#173 fix: 함께쓰기 좋아요 기능 Redis 정합성 수정
  src/main/java/com/hanghae/theham/domain/rental/service/RentalLikeService.java
Labels: fix

#175 feat: 회원 닉네임 중복 검사 기능
  src/main/java/com/hanghae/theham/domain/member/controller/MemberController.java
  src/main/java/com/hanghae/theham/domain/member/controller/docs/MemberControllerDocs.java
  src/main/java/com/hanghae/theham/domain/member/dto/MemberResponseDto.java
  src/main/java/com/hanghae/theham/domain/member/service/MemberService.java
Labels: feature
