Repository The-Ham-Project/BE, pull requests merged in 2024-05, with the labels that each got.

#177 feat: 함께쓰기 목록에 좋아요 표시 기능
  src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
  src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
Labels: feature

#179 feat: 내정보 위치 값 반환
  src/main/java/com/hanghae/theham/domain/member/dto/MemberResponseDto.java
  src/main/java/com/hanghae/theham/domain/member/service/MemberService.java
Labels: feature

#181 fix: update 채팅방 정보 항상 메세지 보낸 사람 기준으로 가는 버그 수정
  src/main/java/com/hanghae/theham/domain/notification/service/NotificationService.java
Labels: fix

#183 refactor: 채팅 예외 발생시 HTTP 에러코드 반환 -> ErrorCode name 반환
  src/main/java/com/hanghae/theham/domain/chat/service/ChatService.java
  src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
  src/main/java/com/hanghae/theham/global/websocket/WebSocketInterceptor.java
  src/main/java/com/hanghae/theham/global/websocket/dto/MessageErrorResponse.java
  src/main/java/com/hanghae/theham/global/websocket/exception/CustomMessageExceptionHandler.java
  src/main/java/com/hanghae/theham/global/websocket/exception/WebSocketException.java
  src/main/java/com/hanghae/theham/global/websocket/exception/WebSocketExceptionHandler.java
Labels: refactoring

#185 feat: 함께쓰기 좋아요 내역 조회
  src/main/java/com/hanghae/theham/domain/member/controller/MemberController.java
  src/main/java/com/hanghae/theham/domain/member/controller/docs/MemberControllerDocs.java
  src/main/java/com/hanghae/theham/domain/member/service/MemberService.java
  src/main/java/com/hanghae/theham/domain/rental/controller/RentalLikeController.java
  src/main/java/com/hanghae/theham/domain/rental/repository/RentalLikeRepository.java
  src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
Labels: feature
